import type { MutationCallsiteId } from './mutationInventory.generated';


export interface MutationOwnerContract {
  owner_component: string;
  owner_state: string;
  loading_state: string;
  catch_policy: string;
  finally_policy: string;
  playwright_case: string;
}

export const mutationOwnerContract = {
  'cancelTaskRun|frontend/src/pages/TaskRunCenter.tsx|cancelRun': {
    owner_component: 'TaskRunCenter',
    owner_state: 'filters, pagination, expandedRowKeys, and details cache',
    loading_state: 'actingRunId',
    catch_policy: 'runMutationWithUX apiErrorMessage -> message.error; preserve task-center owner state',
    finally_policy: 'runMutationWithUX clearLoading: actingRunId',
    playwright_case: 'runtime case: cancel run remote-read-only owner-state case',
  },
  'createAplusGenerateBatch|frontend/src/pages/AplusManagement.tsx|submitGenerate': {
    owner_component: 'AplusManagement',
    owner_state: 'selectedIds, filters, pagination, items, and preview state',
    loading_state: 'submitting',
    catch_policy: 'runMutationWithUX apiErrorMessage -> message.error; preserve selectedIds and current results',
    finally_policy: 'runMutationWithUX clearLoading: submitting',
    playwright_case: 'runtime case: A+ batch generation selection-retention case',
  },
  'createCatalogExportTaskRuns|frontend/src/pages/CatalogList.tsx|createExportTasksByIds': {
    owner_component: 'CatalogList',
    owner_state: 'selectedIds, selectedItemMap, category/view filters, pagination, and current rows',
    loading_state: 'exporting and message loading handle',
    catch_policy: 'runMutationWithUX apiErrorMessage -> message.error; preserve selectedIds and selectedItemMap',
    finally_policy: 'runMutationWithUX clearLoading: exporting and close message loading handle',
    playwright_case: 'runtime case: catalog export selection-retention case',
  },
  'createGigaInventorySyncTaskRuns|frontend/src/pages/InventorySyncList.tsx|handleSync': {
    owner_component: 'InventorySyncList',
    owner_state: 'selectedDataSourceId, filters, pagination, and inventory rows',
    loading_state: 'syncing',
    catch_policy: 'runMutationWithUX apiErrorMessage -> message.error; preserve inventory filters and rows',
    finally_policy: 'runMutationWithUX clearLoading: syncing',
    playwright_case: 'runtime case: inventory sync remote-read-only case',
  },
  'createGigaPriceSyncTaskRuns|frontend/src/pages/InventorySyncList.tsx|handlePriceSync': {
    owner_component: 'InventorySyncList',
    owner_state: 'selectedDataSourceId, filters, pagination, and inventory rows',
    loading_state: 'priceSyncing',
    catch_policy: 'runMutationWithUX apiErrorMessage -> message.error; preserve inventory filters and rows',
    finally_policy: 'runMutationWithUX clearLoading: priceSyncing',
    playwright_case: 'runtime case: price sync remote-read-only case',
  },
  'createGigaPullTaskRuns|frontend/src/pages/ProductList.tsx|pullMissingGigaProducts': {
    owner_component: 'ProductList',
    owner_state: 'filters, pagination, current rows, selectedPullDataSourceIds, pullScope, and pullNewSkuLimit',
    loading_state: 'pullingGigaProducts',
    catch_policy: 'runMutationWithUX apiErrorMessage -> message.error; preserve product-list and pull-modal state',
    finally_policy: 'runMutationWithUX clearLoading: pullingGigaProducts',
    playwright_case: 'runtime case: GIGA pull modal state-retention case',
  },
  'createProduct|frontend/src/pages/CreateProduct.tsx|handleSubmit': {
    owner_component: 'CreateProduct',
    owner_state: 'create-product form fields',
    loading_state: 'loading',
    catch_policy: 'runMutationWithUX apiErrorMessage -> message.error; preserve form fields',
    finally_policy: 'runMutationWithUX clearLoading: loading',
    playwright_case: 'runtime case: create-product form-retention case',
  },
  'createProductBulkAdvanceTaskByFilter|frontend/src/pages/ProductList.tsx|onOk': {
    owner_component: 'ProductList',
    owner_state: 'filters, pagination, current rows, and data-source selection',
    loading_state: 'creatingBulkAdvanceTask and message loading handle',
    catch_policy: 'runMutationWithUX apiErrorMessage -> message.error; preserve current filter contract',
    finally_policy: 'runMutationWithUX clearLoading: creatingBulkAdvanceTask and close message loading handle',
    playwright_case: 'runtime case: bulk-advance filter-retention case',
  },
  'createProductDataSource|frontend/src/pages/ProductDataSourceList.tsx|save': {
    owner_component: 'ProductDataSourceList',
    owner_state: 'data-source form, editing record, modal state, and current rows',
    loading_state: 'saving',
    catch_policy: 'runMutationWithUX apiErrorMessage -> message.error; preserve form and modal state',
    finally_policy: 'runMutationWithUX clearLoading: saving',
    playwright_case: 'runtime case: create data-source form-retention case',
  },
  'deleteCatalogTemplateFile|frontend/src/pages/CatalogList.tsx|deleteTemplateFile': {
    owner_component: 'CatalogList',
    owner_state: 'template files, category/view filters, selectedIds, selectedItemMap, and pending upload file',
    loading_state: 'templateFileMutatingId',
    catch_policy: 'runMutationWithUX apiErrorMessage -> message.error; preserve template and selection state',
    finally_policy: 'runMutationWithUX clearLoading: templateFileMutatingId',
    playwright_case: 'runtime case: template deletion owner-state case',
  },
  'deleteProduct|frontend/src/pages/ProductDetail.tsx|handleDelete': {
    owner_component: 'ProductDetail',
    owner_state: 'product, activeTabKey, listingTitleInput, selectedCategoryKey, and regenReason',
    loading_state: 'deleting',
    catch_policy: 'runMutationWithUX apiErrorMessage -> message.error; preserve loaded detail and drafts',
    finally_policy: 'runMutationWithUX clearLoading: deleting',
    playwright_case: 'runtime case: product-detail delete state-retention case',
  },
  'deleteProduct|frontend/src/pages/ProductList.tsx|handleDeleteProduct': {
    owner_component: 'ProductList',
    owner_state: 'filters, pagination, selected rows, and current data',
    loading_state: 'deletingId',
    catch_policy: 'runMutationWithUX apiErrorMessage -> message.error; preserve product-list owner state',
    finally_policy: 'runMutationWithUX clearLoading: deletingId',
    playwright_case: 'runtime case: product-list delete state-retention case',
  },
  'deleteProductDataSource|frontend/src/pages/ProductDataSourceList.tsx|remove': {
    owner_component: 'ProductDataSourceList',
    owner_state: 'current rows, form, editing record, and modal state',
    loading_state: 'deletingId',
    catch_policy: 'runMutationWithUX apiErrorMessage -> message.error; preserve current rows and editor state',
    finally_policy: 'runMutationWithUX clearLoading: deletingId',
    playwright_case: 'runtime case: delete data-source owner-state case',
  },
  'extractProductZip|frontend/src/pages/ProductDetail.tsx|extractZip': {
    owner_component: 'ProductDetail',
    owner_state: 'product, activeTabKey, listingTitleInput, and listingImageDraftPaths',
    loading_state: 'zipExtractingPath',
    catch_policy: 'runMutationWithUX apiErrorMessage -> message.error; preserve loaded detail and drafts',
    finally_policy: 'runMutationWithUX clearLoading: zipExtractingPath',
    playwright_case: 'runtime case: zip extract detail-retention case',
  },
  'importLocalEnvConfig|frontend/src/components/LocalEnvConfigTable.tsx|importConfig': {
    owner_component: 'LocalEnvConfigTable',
    owner_state: 'items, importOpen, and importContent',
    loading_state: 'saving',
    catch_policy: 'runMutationWithUX apiErrorMessage -> message.error; preserve import text and loaded rows',
    finally_policy: 'runMutationWithUX clearLoading: saving',
    playwright_case: 'runtime case: local environment import state-retention case',
  },
  'generateProductAplus|frontend/src/pages/ProductDetail.tsx|generateAplus': {
    owner_component: 'ProductDetail',
    owner_state: 'product, activeTabKey, regenReason, listingTitleInput, and listingImageDraftPaths',
    loading_state: 'aplusGenerateLoading',
    catch_policy: 'runMutationWithUX apiErrorMessage -> message.error; preserve detail and draft state',
    finally_policy: 'runMutationWithUX clearLoading: aplusGenerateLoading',
    playwright_case: 'runtime case: product A+ generation draft-retention case',
  },
  'importUpcPool|frontend/src/pages/UpcPoolPage.tsx|handleAdd': {
    owner_component: 'UpcPoolPage',
    owner_state: 'UPC form text, filters, pagination, summary, and current rows',
    loading_state: 'saving',
    catch_policy: 'runMutationWithUX apiErrorMessage -> message.error; preserve UPC form and current results',
    finally_policy: 'runMutationWithUX clearLoading: saving',
    playwright_case: 'runtime case: UPC import form-retention case',
  },
  'markTaskRunInterrupted|frontend/src/pages/TaskRunCenter.tsx|markInterrupted': {
    owner_component: 'TaskRunCenter',
    owner_state: 'filters, pagination, expandedRowKeys, and details cache',
    loading_state: 'actingRunId',
    catch_policy: 'runMutationWithUX apiErrorMessage -> message.error; preserve task-center owner state',
    finally_policy: 'runMutationWithUX clearLoading: actingRunId',
    playwright_case: 'runtime case: mark-interrupted owner-state case',
  },
  'openProductFile|frontend/src/pages/ProductDetail.tsx|openPath': {
    owner_component: 'ProductDetail',
    owner_state: 'product, activeTabKey, listingTitleInput, and listingImageDraftPaths',
    loading_state: 'fileOpening path/operation key string; clear null',
    catch_policy: 'runMutationWithUX apiErrorMessage -> message.error; preserve loaded detail and drafts',
    finally_policy: 'runMutationWithUX clearLoading: fileOpening to null',
    playwright_case: 'runtime case: file-open detail-retention case',
  },
  'pauseOfflineTask|frontend/src/pages/OfflineTaskCenter.tsx|pauseTask': {
    owner_component: 'OfflineTaskCenter',
    owner_state: 'filters, pagination, expanded rows, and details cache',
    loading_state: 'pausingId',
    catch_policy: 'runMutationWithUX apiErrorMessage -> message.error; preserve offline-task owner state',
    finally_policy: 'runMutationWithUX clearLoading: pausingId',
    playwright_case: 'runtime case: offline-task pause owner-state case',
  },
  'pausePipeline|frontend/src/pages/ProductDetail.tsx|ProductDetail|1': {
    owner_component: 'ProductDetail',
    owner_state: 'product, activeTabKey, listingTitleInput, selectedCategoryKey, listingImageDraftPaths, and regenReason',
    loading_state: 'pipelineRetryLoading',
    catch_policy: 'runMutationWithUX apiErrorMessage -> message.error; preserve loaded detail and drafts',
    finally_policy: 'runMutationWithUX clearLoading: pipelineRetryLoading',
    playwright_case: 'runtime case: running product pause detail-retention case',
  },
  'pausePipeline|frontend/src/pages/ProductDetail.tsx|ProductDetail|2': {
    owner_component: 'ProductDetail',
    owner_state: 'product, activeTabKey, listingTitleInput, selectedCategoryKey, listingImageDraftPaths, and regenReason',
    loading_state: 'pipelineRetryLoading',
    catch_policy: 'runMutationWithUX apiErrorMessage -> message.error; preserve loaded detail and drafts',
    finally_policy: 'runMutationWithUX clearLoading: pipelineRetryLoading',
    playwright_case: 'runtime case: confirm-triggered product pause detail-retention case',
  },
  'pausePipeline|frontend/src/pages/ProductList.tsx|suspendProductTask': {
    owner_component: 'ProductList',
    owner_state: 'filters, pagination, selected rows, and current data',
    loading_state: 'rerunningId',
    catch_policy: 'runMutationWithUX apiErrorMessage -> message.error; preserve product-list owner state',
    finally_policy: 'runMutationWithUX clearLoading: rerunningId',
    playwright_case: 'runtime case: product-list pause state-retention case',
  },
  'regenerateAplusModule|frontend/src/pages/ProductDetail.tsx|regenerateAplus': {
    owner_component: 'ProductDetail',
    owner_state: 'regenTarget, regenReason, loaded detail, active tab, and A+ draft',
    loading_state: 'regenLoading',
    catch_policy: 'runMutationWithUX apiErrorMessage -> message.error; preserve regeneration target and reason',
    finally_policy: 'runMutationWithUX clearLoading: regenLoading',
    playwright_case: 'runtime case: A+ regeneration reason-retention case',
  },
  'rerunOfflineTask|frontend/src/pages/OfflineTaskCenter.tsx|rerunTask': {
    owner_component: 'OfflineTaskCenter',
    owner_state: 'filters, pagination, expanded rows, and details cache',
    loading_state: 'rerunningId',
    catch_policy: 'runMutationWithUX apiErrorMessage -> message.error; preserve offline-task owner state',
    finally_policy: 'runMutationWithUX clearLoading: rerunningId',
    playwright_case: 'runtime case: offline-task rerun owner-state case',
  },
  'restartPipeline|frontend/src/pages/ProductDetail.tsx|doRestart': {
    owner_component: 'ProductDetail',
    owner_state: 'product, activeTabKey, listingTitleInput, selectedCategoryKey, listingImageDraftPaths, and regenReason',
    loading_state: 'restartLoading',
    catch_policy: 'runMutationWithUX apiErrorMessage -> message.error; preserve loaded detail and drafts',
    finally_policy: 'runMutationWithUX clearLoading: restartLoading',
    playwright_case: 'runtime case: product-detail restart state-retention case',
  },
  'restartPipeline|frontend/src/pages/ProductList.tsx|render': {
    owner_component: 'ProductList',
    owner_state: 'filters, pagination, selected rows, and current data',
    loading_state: 'rerunningId',
    catch_policy: 'runMutationWithUX apiErrorMessage -> message.error; preserve product-list owner state',
    finally_policy: 'runMutationWithUX clearLoading: rerunningId',
    playwright_case: 'runtime case: product-list restart state-retention case',
  },
  'resumeOfflineTask|frontend/src/pages/OfflineTaskCenter.tsx|resumeTask': {
    owner_component: 'OfflineTaskCenter',
    owner_state: 'filters, pagination, expanded rows, and details cache',
    loading_state: 'resumingId',
    catch_policy: 'runMutationWithUX apiErrorMessage -> message.error; preserve offline-task owner state',
    finally_policy: 'runMutationWithUX clearLoading: resumingId',
    playwright_case: 'runtime case: offline-task resume owner-state case',
  },
  'resumePipeline|frontend/src/pages/ProductDetail.tsx|ProductDetail|1': {
    owner_component: 'ProductDetail',
    owner_state: 'product, activeTabKey, listingTitleInput, selectedCategoryKey, listingImageDraftPaths, and regenReason',
    loading_state: 'pipelineRetryLoading',
    catch_policy: 'runMutationWithUX apiErrorMessage -> message.error; preserve loaded detail and drafts',
    finally_policy: 'runMutationWithUX clearLoading: pipelineRetryLoading',
    playwright_case: 'runtime case: paused product resume detail-retention case',
  },
  'resumePipeline|frontend/src/pages/ProductDetail.tsx|ProductDetail|2': {
    owner_component: 'ProductDetail',
    owner_state: 'product, activeTabKey, listingTitleInput, selectedCategoryKey, listingImageDraftPaths, and regenReason',
    loading_state: 'pipelineRetryLoading',
    catch_policy: 'runMutationWithUX apiErrorMessage -> message.error; preserve loaded detail and drafts',
    finally_policy: 'runMutationWithUX clearLoading: pipelineRetryLoading',
    playwright_case: 'runtime case: review product resume detail-retention case',
  },
  'resumePipeline|frontend/src/pages/ProductList.tsx|resumeProductTask': {
    owner_component: 'ProductList',
    owner_state: 'filters, pagination, selected rows, and current data',
    loading_state: 'rerunningId',
    catch_policy: 'runMutationWithUX apiErrorMessage -> message.error; preserve product-list owner state',
    finally_policy: 'runMutationWithUX clearLoading: rerunningId',
    playwright_case: 'runtime case: product-list resume state-retention case',
  },
  'resumePipeline|frontend/src/pages/ProductDetail.tsx|runWorkflowAction': {
    owner_component: 'ProductDetail',
    owner_state: 'product, activeTabKey, listingTitleInput, selectedCategoryKey, listingImageDraftPaths, and regenReason',
    loading_state: 'pipelineRetryLoading for API workflow actions',
    catch_policy: 'runMutationWithUX apiErrorMessage -> message.error; preserve loaded detail and drafts',
    finally_policy: 'runMutationWithUX clearLoading: pipelineRetryLoading for the API workflow action',
    playwright_case: 'runtime case: workflow resume on product detail state-retention case',
  },
  'resumePipeline|frontend/src/pages/ProductList.tsx|runProductWorkflowAction': {
    owner_component: 'ProductList',
    owner_state: 'filters, pagination, selected rows, current data, and workflow row context',
    loading_state: 'rerunningId for API workflow actions',
    catch_policy: 'runMutationWithUX apiErrorMessage -> message.error; preserve product-list owner state',
    finally_policy: 'runMutationWithUX clearLoading: rerunningId for the API workflow action',
    playwright_case: 'runtime case: workflow resume on product list state-retention case',
  },
  'retryProductAutoImageSelection|frontend/src/pages/ProductDetail.tsx|runWorkflowAction': {
    owner_component: 'ProductDetail',
    owner_state: 'product, activeTabKey, listingTitleInput, selectedCategoryKey, listingImageDraftPaths, and regenReason',
    loading_state: 'pipelineRetryLoading for API workflow actions',
    catch_policy: 'runMutationWithUX apiErrorMessage -> message.error; preserve loaded detail and drafts',
    finally_policy: 'runMutationWithUX clearLoading: pipelineRetryLoading for the API workflow action',
    playwright_case: 'runtime case: workflow auto-image retry on product detail state-retention case',
  },
  'retryProductAutoImageSelection|frontend/src/pages/ProductList.tsx|runProductWorkflowAction': {
    owner_component: 'ProductList',
    owner_state: 'filters, pagination, selected rows, current data, and workflow row context',
    loading_state: 'rerunningId for API workflow actions',
    catch_policy: 'runMutationWithUX apiErrorMessage -> message.error; preserve product-list owner state',
    finally_policy: 'runMutationWithUX clearLoading: rerunningId for the API workflow action',
    playwright_case: 'runtime case: workflow auto-image retry on product list state-retention case',
  },
  'retryProductCompetitorSearch|frontend/src/pages/ProductDetail.tsx|runWorkflowAction': {
    owner_component: 'ProductDetail',
    owner_state: 'product, activeTabKey, listingTitleInput, selectedCategoryKey, listingImageDraftPaths, and regenReason',
    loading_state: 'pipelineRetryLoading for API workflow actions',
    catch_policy: 'runMutationWithUX apiErrorMessage -> message.error; preserve loaded detail and drafts',
    finally_policy: 'runMutationWithUX clearLoading: pipelineRetryLoading for the API workflow action',
    playwright_case: 'runtime case: workflow competitor-search retry on product detail state-retention case',
  },
  'retryProductCompetitorSearch|frontend/src/pages/ProductList.tsx|runProductWorkflowAction': {
    owner_component: 'ProductList',
    owner_state: 'filters, pagination, selected rows, current data, and workflow row context',
    loading_state: 'rerunningId for API workflow actions',
    catch_policy: 'runMutationWithUX apiErrorMessage -> message.error; preserve product-list owner state',
    finally_policy: 'runMutationWithUX clearLoading: rerunningId for the API workflow action',
    playwright_case: 'runtime case: workflow competitor-search retry on product list state-retention case',
  },
  'retryProductCompetitorVisualMatch|frontend/src/pages/ProductDetail.tsx|runWorkflowAction': {
    owner_component: 'ProductDetail',
    owner_state: 'product, activeTabKey, listingTitleInput, selectedCategoryKey, listingImageDraftPaths, and regenReason',
    loading_state: 'pipelineRetryLoading for API workflow actions',
    catch_policy: 'runMutationWithUX apiErrorMessage -> message.error; preserve loaded detail and drafts',
    finally_policy: 'runMutationWithUX clearLoading: pipelineRetryLoading for the API workflow action',
    playwright_case: 'runtime case: workflow visual-match retry on product detail state-retention case',
  },
  'retryProductCompetitorVisualMatch|frontend/src/pages/ProductList.tsx|runProductWorkflowAction': {
    owner_component: 'ProductList',
    owner_state: 'filters, pagination, selected rows, current data, and workflow row context',
    loading_state: 'rerunningId for API workflow actions',
    catch_policy: 'runMutationWithUX apiErrorMessage -> message.error; preserve product-list owner state',
    finally_policy: 'runMutationWithUX clearLoading: rerunningId for the API workflow action',
    playwright_case: 'runtime case: workflow visual-match retry on product list state-retention case',
  },
  'retryStep|frontend/src/pages/ProductDetail.tsx|runWorkflowAction': {
    owner_component: 'ProductDetail',
    owner_state: 'product, activeTabKey, listingTitleInput, selectedCategoryKey, listingImageDraftPaths, and regenReason',
    loading_state: 'pipelineRetryLoading for API workflow actions',
    catch_policy: 'runMutationWithUX apiErrorMessage -> message.error; preserve loaded detail and drafts',
    finally_policy: 'runMutationWithUX clearLoading: pipelineRetryLoading for the API workflow action',
    playwright_case: 'runtime case: workflow retry on product detail state-retention case',
  },
  'retryStep|frontend/src/pages/ProductList.tsx|runProductWorkflowAction': {
    owner_component: 'ProductList',
    owner_state: 'filters, pagination, selected rows, current data, and workflow row context',
    loading_state: 'rerunningId for API workflow actions',
    catch_policy: 'runMutationWithUX apiErrorMessage -> message.error; preserve product-list owner state',
    finally_policy: 'runMutationWithUX clearLoading: rerunningId for the API workflow action',
    playwright_case: 'runtime case: workflow retry on product list state-retention case',
  },
  'retryAplusRegeneration|frontend/src/pages/ProductDetail.tsx|retryInterruptedAplus': {
    owner_component: 'ProductDetail',
    owner_state: 'product, activeTabKey, regenReason, listingTitleInput, and listingImageDraftPaths',
    loading_state: 'regenRetryLoading',
    catch_policy: 'runMutationWithUX apiErrorMessage -> message.error; preserve detail and draft state',
    finally_policy: 'runMutationWithUX clearLoading: regenRetryLoading',
    playwright_case: 'runtime case: A+ retry detail-retention case',
  },
  'retryFailedTaskRunSteps|frontend/src/pages/TaskRunCenter.tsx|retryRun': {
    owner_component: 'TaskRunCenter',
    owner_state: 'filters, pagination, expandedRowKeys, and details cache',
    loading_state: 'retryingId',
    catch_policy: 'runMutationWithUX apiErrorMessage -> message.error; preserve task-center owner state',
    finally_policy: 'runMutationWithUX clearLoading: retryingId',
    playwright_case: 'runtime case: task-run retry owner-state case',
  },
  'retryStep|frontend/src/pages/ProductDetail.tsx|ProductDetail': {
    owner_component: 'ProductDetail',
    owner_state: 'product, activeTabKey, listingTitleInput, selectedCategoryKey, listingImageDraftPaths, and regenReason',
    loading_state: 'pipelineRetryLoading',
    catch_policy: 'runMutationWithUX apiErrorMessage -> message.error; preserve loaded detail and drafts',
    finally_policy: 'runMutationWithUX clearLoading: pipelineRetryLoading',
    playwright_case: 'runtime case: legacy product-detail retry state-retention case',
  },
  'retryStep|frontend/src/pages/ProductList.tsx|renderPrimaryRowAction|1': {
    owner_component: 'ProductList',
    owner_state: 'filters, pagination, selected rows, and current data',
    loading_state: 'rerunningId',
    catch_policy: 'runMutationWithUX apiErrorMessage -> message.error; preserve product-list owner state',
    finally_policy: 'runMutationWithUX clearLoading: rerunningId',
    playwright_case: 'runtime case: interrupted product-list retry state-retention case',
  },
  'retryStep|frontend/src/pages/ProductList.tsx|renderPrimaryRowAction|2': {
    owner_component: 'ProductList',
    owner_state: 'filters, pagination, selected rows, and current data',
    loading_state: 'rerunningId',
    catch_policy: 'runMutationWithUX apiErrorMessage -> message.error; preserve product-list owner state',
    finally_policy: 'runMutationWithUX clearLoading: rerunningId',
    playwright_case: 'runtime case: failed product-list retry state-retention case',
  },
  'retryTaskStep|frontend/src/pages/TaskRunCenter.tsx|retryOneStep': {
    owner_component: 'TaskRunCenter',
    owner_state: 'filters, pagination, expandedRowKeys, and details cache',
    loading_state: 'retryingId',
    catch_policy: 'runMutationWithUX apiErrorMessage -> message.error; preserve task-center owner state',
    finally_policy: 'runMutationWithUX clearLoading: retryingId',
    playwright_case: 'runtime case: task-step retry owner-state case',
  },
  'runProductFromStep|frontend/src/pages/ProductDetail.tsx|regenerateListing': {
    owner_component: 'ProductDetail',
    owner_state: 'listingTitleInput, listingBulletsInput, product, activeTabKey, listingImageDraftPaths, and regenReason',
    loading_state: 'listingRegenerateLoading',
    catch_policy: 'runMutationWithUX apiErrorMessage -> message.error; preserve listing fields and loaded detail',
    finally_policy: 'runMutationWithUX clearLoading: listingRegenerateLoading',
    playwright_case: 'runtime case: listing regeneration draft-retention case',
  },
  'runProductFromStep|frontend/src/pages/ProductDetail.tsx|retryInterruptedPipeline': {
    owner_component: 'ProductDetail',
    owner_state: 'product, activeTabKey, listingTitleInput, selectedCategoryKey, listingImageDraftPaths, and regenReason',
    loading_state: 'pipelineRetryLoading',
    catch_policy: 'runMutationWithUX apiErrorMessage -> message.error; preserve loaded detail and drafts',
    finally_policy: 'runMutationWithUX clearLoading: pipelineRetryLoading',
    playwright_case: 'runtime case: interrupted pipeline retry state-retention case',
  },
  'updateCatalogTemplateFileStatus|frontend/src/pages/CatalogList.tsx|toggleTemplateFile': {
    owner_component: 'CatalogList',
    owner_state: 'template files, category/view filters, selectedIds, selectedItemMap, and pending upload file',
    loading_state: 'templateFileMutatingId',
    catch_policy: 'runMutationWithUX apiErrorMessage -> message.error; preserve template and selection state',
    finally_policy: 'runMutationWithUX clearLoading: templateFileMutatingId',
    playwright_case: 'runtime case: template enablement owner-state case',
  },
  'updateConfig|frontend/src/pages/ConfigPage.tsx|saveConfig': {
    owner_component: 'ConfigPage',
    owner_state: 'configuration form values and loaded configuration',
    loading_state: 'saving',
    catch_policy: 'runMutationWithUX apiErrorMessage -> message.error; preserve configuration form values',
    finally_policy: 'runMutationWithUX clearLoading: saving',
    playwright_case: 'runtime case: configuration form-retention case',
  },
  'updateLocalEnvValue|frontend/src/components/LocalEnvConfigTable.tsx|saveValue': {
    owner_component: 'LocalEnvConfigTable',
    owner_state: 'items, editing, and form',
    loading_state: 'saving',
    catch_policy: 'runMutationWithUX apiErrorMessage -> message.error; preserve the edit draft and loaded rows',
    finally_policy: 'runMutationWithUX clearLoading: saving',
    playwright_case: 'runtime case: local environment value state-retention case',
  },
  'updateProduct|frontend/src/pages/ProductDetail.tsx|saveCategory': {
    owner_component: 'ProductDetail',
    owner_state: 'selectedCategoryKey, categoryOptions, category modal, loaded detail, and active tab',
    loading_state: 'categorySaving',
    catch_policy: 'runMutationWithUX apiErrorMessage -> message.error; preserve category draft and modal state',
    finally_policy: 'runMutationWithUX clearLoading: categorySaving',
    playwright_case: 'runtime case: category draft-retention case',
  },
  'updateProduct|frontend/src/pages/ProductDetail.tsx|saveListing': {
    owner_component: 'ProductDetail',
    owner_state: 'listingTitleInput, listingBulletsInput, listingEditOpen, product, and activeTabKey',
    loading_state: 'listingSaving',
    catch_policy: 'runMutationWithUX apiErrorMessage -> message.error; preserve all listing draft fields',
    finally_policy: 'runMutationWithUX clearLoading: listingSaving',
    playwright_case: 'runtime case: listing form-retention case',
  },
  'updateProductDataSource|frontend/src/pages/ProductDataSourceList.tsx|save': {
    owner_component: 'ProductDataSourceList',
    owner_state: 'data-source form, editing record, modal state, and current rows',
    loading_state: 'saving',
    catch_policy: 'runMutationWithUX apiErrorMessage -> message.error; preserve form and modal state',
    finally_policy: 'runMutationWithUX clearLoading: saving',
    playwright_case: 'runtime case: update data-source form-retention case',
  },
  'updateProductListingImages|frontend/src/pages/ProductDetail.tsx|saveListingImagePaths': {
    owner_component: 'ProductDetail',
    owner_state: 'listingImageDraftPaths, listingImageDirty, loaded detail, and active tab',
    loading_state: 'imageOrderSaving',
    catch_policy: 'runMutationWithUX apiErrorMessage -> message.error; preserve the listing image draft',
    finally_policy: 'runMutationWithUX clearLoading: imageOrderSaving',
    playwright_case: 'runtime case: product-detail image-draft retention case',
  },
  'updateProductListingImages|frontend/src/pages/ProductImageReview.tsx|saveAndNext': {
    owner_component: 'ProductImageReview',
    owner_state: 'draftPaths, currentId, queue, queueTotal, and detail',
    loading_state: 'saving',
    catch_policy: 'runMutationWithUX apiErrorMessage -> message.error; preserve image draft, queue, and detail',
    finally_policy: 'runMutationWithUX clearLoading: saving',
    playwright_case: 'runtime case: image-review draft-retention case',
  },
  'uploadCatalogCategoryTemplate|frontend/src/pages/CatalogList.tsx|uploadTemplateForCategory': {
    owner_component: 'CatalogList',
    owner_state: 'pending upload file, template category, category/view filters, selectedIds, and selectedItemMap',
    loading_state: 'templateUploading category key string; clear null',
    catch_policy: 'runMutationWithUX apiErrorMessage -> message.error; preserve the pending file and selection state',
    finally_policy: 'runMutationWithUX clearLoading: templateUploading to null',
    playwright_case: 'runtime case: template-upload file-retention case',
  },
  'wakeTaskRun|frontend/src/pages/TaskRunCenter.tsx|wakeRun': {
    owner_component: 'TaskRunCenter',
    owner_state: 'filters, pagination, expandedRowKeys, and details cache',
    loading_state: 'actingRunId',
    catch_policy: 'runMutationWithUX apiErrorMessage -> message.error; preserve task-center owner state',
    finally_policy: 'runMutationWithUX clearLoading: actingRunId',
    playwright_case: 'runtime case: wake task-run owner-state case',
  },
} satisfies Record<MutationCallsiteId, MutationOwnerContract>;
