/* This file is generated by scripts/generate-mutation-inventory.mjs. */
/* D2b static wrapper coverage: enabled. Runtime Playwright coverage: enabled. */

export interface MutationCallsite {
  id: string;
  client: string;
  endpoint: string;
  method: 'post' | 'put' | 'patch' | 'delete';
  source: string;
  handler: string;
  via: 'direct' | 'workflow_registry';
}

export type MutationCallsiteId =
  | "cancelTaskRun|frontend/src/pages/TaskRunCenter.tsx|cancelRun"
  | "createAplusGenerateBatch|frontend/src/pages/AplusManagement.tsx|submitGenerate"
  | "createCatalogExportTaskRuns|frontend/src/pages/CatalogList.tsx|createExportTasksByIds"
  | "createGigaInventorySyncTaskRuns|frontend/src/pages/InventorySyncList.tsx|handleSync"
  | "createGigaPriceSyncTaskRuns|frontend/src/pages/InventorySyncList.tsx|handlePriceSync"
  | "createGigaPullTaskRuns|frontend/src/pages/ProductList.tsx|pullMissingGigaProducts"
  | "createProduct|frontend/src/pages/CreateProduct.tsx|handleSubmit"
  | "createProductBulkAdvanceTaskByFilter|frontend/src/pages/ProductList.tsx|onOk"
  | "createProductDataSource|frontend/src/pages/ProductDataSourceList.tsx|save"
  | "deleteCatalogTemplateFile|frontend/src/pages/CatalogList.tsx|deleteTemplateFile"
  | "deleteProduct|frontend/src/pages/ProductDetail.tsx|handleDelete"
  | "deleteProduct|frontend/src/pages/ProductList.tsx|handleDeleteProduct"
  | "deleteProductDataSource|frontend/src/pages/ProductDataSourceList.tsx|remove"
  | "extractProductZip|frontend/src/pages/ProductDetail.tsx|extractZip"
  | "generateProductAplus|frontend/src/pages/ProductDetail.tsx|generateAplus"
  | "importLocalEnvConfig|frontend/src/components/LocalEnvConfigTable.tsx|importConfig"
  | "importUpcPool|frontend/src/pages/UpcPoolPage.tsx|handleAdd"
  | "markTaskRunInterrupted|frontend/src/pages/TaskRunCenter.tsx|markInterrupted"
  | "openProductFile|frontend/src/pages/ProductDetail.tsx|openPath"
  | "pauseOfflineTask|frontend/src/pages/OfflineTaskCenter.tsx|pauseTask"
  | "pausePipeline|frontend/src/pages/ProductDetail.tsx|ProductDetail|1"
  | "pausePipeline|frontend/src/pages/ProductDetail.tsx|ProductDetail|2"
  | "pausePipeline|frontend/src/pages/ProductList.tsx|suspendProductTask"
  | "regenerateAplusModule|frontend/src/pages/ProductDetail.tsx|regenerateAplus"
  | "rerunOfflineTask|frontend/src/pages/OfflineTaskCenter.tsx|rerunTask"
  | "restartPipeline|frontend/src/pages/ProductDetail.tsx|doRestart"
  | "restartPipeline|frontend/src/pages/ProductList.tsx|render"
  | "resumeOfflineTask|frontend/src/pages/OfflineTaskCenter.tsx|resumeTask"
  | "resumePipeline|frontend/src/pages/ProductDetail.tsx|ProductDetail|1"
  | "resumePipeline|frontend/src/pages/ProductDetail.tsx|ProductDetail|2"
  | "resumePipeline|frontend/src/pages/ProductDetail.tsx|runWorkflowAction"
  | "resumePipeline|frontend/src/pages/ProductList.tsx|resumeProductTask"
  | "resumePipeline|frontend/src/pages/ProductList.tsx|runProductWorkflowAction"
  | "retryAplusRegeneration|frontend/src/pages/ProductDetail.tsx|retryInterruptedAplus"
  | "retryFailedTaskRunSteps|frontend/src/pages/TaskRunCenter.tsx|retryRun"
  | "retryProductAutoImageSelection|frontend/src/pages/ProductDetail.tsx|runWorkflowAction"
  | "retryProductAutoImageSelection|frontend/src/pages/ProductList.tsx|runProductWorkflowAction"
  | "retryProductCompetitorSearch|frontend/src/pages/ProductDetail.tsx|runWorkflowAction"
  | "retryProductCompetitorSearch|frontend/src/pages/ProductList.tsx|runProductWorkflowAction"
  | "retryProductCompetitorVisualMatch|frontend/src/pages/ProductDetail.tsx|runWorkflowAction"
  | "retryProductCompetitorVisualMatch|frontend/src/pages/ProductList.tsx|runProductWorkflowAction"
  | "retryStep|frontend/src/pages/ProductDetail.tsx|ProductDetail"
  | "retryStep|frontend/src/pages/ProductDetail.tsx|runWorkflowAction"
  | "retryStep|frontend/src/pages/ProductList.tsx|renderPrimaryRowAction|1"
  | "retryStep|frontend/src/pages/ProductList.tsx|renderPrimaryRowAction|2"
  | "retryStep|frontend/src/pages/ProductList.tsx|runProductWorkflowAction"
  | "retryTaskStep|frontend/src/pages/TaskRunCenter.tsx|retryOneStep"
  | "runPipelineStep|frontend/src/pages/ProductDetail.tsx|generateCustomerMindset"
  | "runProductFromStep|frontend/src/pages/ProductDetail.tsx|regenerateListing"
  | "runProductFromStep|frontend/src/pages/ProductDetail.tsx|retryInterruptedPipeline"
  | "updateCatalogTemplateFileStatus|frontend/src/pages/CatalogList.tsx|toggleTemplateFile"
  | "updateConfig|frontend/src/pages/ConfigPage.tsx|saveConfig"
  | "updateLocalEnvValue|frontend/src/components/LocalEnvConfigTable.tsx|saveValue"
  | "updateProduct|frontend/src/pages/ProductDetail.tsx|saveCategory"
  | "updateProduct|frontend/src/pages/ProductDetail.tsx|saveListing"
  | "updateProductDataSource|frontend/src/pages/ProductDataSourceList.tsx|save"
  | "updateProductListingImages|frontend/src/pages/ProductDetail.tsx|saveListingImagePaths"
  | "updateProductListingImages|frontend/src/pages/ProductImageReview.tsx|saveAndNext"
  | "uploadCatalogCategoryTemplate|frontend/src/pages/CatalogList.tsx|uploadTemplateForCategory"
  | "wakeTaskRun|frontend/src/pages/TaskRunCenter.tsx|wakeRun";

export const mutationInventory = [
  {
    "id": "cancelTaskRun|frontend/src/pages/TaskRunCenter.tsx|cancelRun",
    "client": "cancelTaskRun",
    "endpoint": "`/task-runs/${id}/cancel`",
    "method": "post",
    "source": "frontend/src/pages/TaskRunCenter.tsx",
    "handler": "cancelRun",
    "via": "direct"
  },
  {
    "id": "createAplusGenerateBatch|frontend/src/pages/AplusManagement.tsx|submitGenerate",
    "client": "createAplusGenerateBatch",
    "endpoint": "'/products/catalog/aplus-generate'",
    "method": "post",
    "source": "frontend/src/pages/AplusManagement.tsx",
    "handler": "submitGenerate",
    "via": "direct"
  },
  {
    "id": "createCatalogExportTaskRuns|frontend/src/pages/CatalogList.tsx|createExportTasksByIds",
    "client": "createCatalogExportTaskRuns",
    "endpoint": "'/task-runs/catalog-export'",
    "method": "post",
    "source": "frontend/src/pages/CatalogList.tsx",
    "handler": "createExportTasksByIds",
    "via": "direct"
  },
  {
    "id": "createGigaInventorySyncTaskRuns|frontend/src/pages/InventorySyncList.tsx|handleSync",
    "client": "createGigaInventorySyncTaskRuns",
    "endpoint": "'/task-runs/giga-inventory-sync'",
    "method": "post",
    "source": "frontend/src/pages/InventorySyncList.tsx",
    "handler": "handleSync",
    "via": "direct"
  },
  {
    "id": "createGigaPriceSyncTaskRuns|frontend/src/pages/InventorySyncList.tsx|handlePriceSync",
    "client": "createGigaPriceSyncTaskRuns",
    "endpoint": "'/task-runs/giga-price-sync'",
    "method": "post",
    "source": "frontend/src/pages/InventorySyncList.tsx",
    "handler": "handlePriceSync",
    "via": "direct"
  },
  {
    "id": "createGigaPullTaskRuns|frontend/src/pages/ProductList.tsx|pullMissingGigaProducts",
    "client": "createGigaPullTaskRuns",
    "endpoint": "'/task-runs/giga-pull'",
    "method": "post",
    "source": "frontend/src/pages/ProductList.tsx",
    "handler": "pullMissingGigaProducts",
    "via": "direct"
  },
  {
    "id": "createProduct|frontend/src/pages/CreateProduct.tsx|handleSubmit",
    "client": "createProduct",
    "endpoint": "'/products'",
    "method": "post",
    "source": "frontend/src/pages/CreateProduct.tsx",
    "handler": "handleSubmit",
    "via": "direct"
  },
  {
    "id": "createProductBulkAdvanceTaskByFilter|frontend/src/pages/ProductList.tsx|onOk",
    "client": "createProductBulkAdvanceTaskByFilter",
    "endpoint": "'/products/bulk-advance-task/by-filter'",
    "method": "post",
    "source": "frontend/src/pages/ProductList.tsx",
    "handler": "onOk",
    "via": "direct"
  },
  {
    "id": "createProductDataSource|frontend/src/pages/ProductDataSourceList.tsx|save",
    "client": "createProductDataSource",
    "endpoint": "'/product-data-sources'",
    "method": "post",
    "source": "frontend/src/pages/ProductDataSourceList.tsx",
    "handler": "save",
    "via": "direct"
  },
  {
    "id": "deleteCatalogTemplateFile|frontend/src/pages/CatalogList.tsx|deleteTemplateFile",
    "client": "deleteCatalogTemplateFile",
    "endpoint": "`/products/catalog/template-files/${fileId}`",
    "method": "delete",
    "source": "frontend/src/pages/CatalogList.tsx",
    "handler": "deleteTemplateFile",
    "via": "direct"
  },
  {
    "id": "deleteProduct|frontend/src/pages/ProductDetail.tsx|handleDelete",
    "client": "deleteProduct",
    "endpoint": "`/products/${id}`",
    "method": "delete",
    "source": "frontend/src/pages/ProductDetail.tsx",
    "handler": "handleDelete",
    "via": "direct"
  },
  {
    "id": "deleteProduct|frontend/src/pages/ProductList.tsx|handleDeleteProduct",
    "client": "deleteProduct",
    "endpoint": "`/products/${id}`",
    "method": "delete",
    "source": "frontend/src/pages/ProductList.tsx",
    "handler": "handleDeleteProduct",
    "via": "direct"
  },
  {
    "id": "deleteProductDataSource|frontend/src/pages/ProductDataSourceList.tsx|remove",
    "client": "deleteProductDataSource",
    "endpoint": "`/product-data-sources/${id}`",
    "method": "delete",
    "source": "frontend/src/pages/ProductDataSourceList.tsx",
    "handler": "remove",
    "via": "direct"
  },
  {
    "id": "extractProductZip|frontend/src/pages/ProductDetail.tsx|extractZip",
    "client": "extractProductZip",
    "endpoint": "`/products/${id}/files/extract`",
    "method": "post",
    "source": "frontend/src/pages/ProductDetail.tsx",
    "handler": "extractZip",
    "via": "direct"
  },
  {
    "id": "generateProductAplus|frontend/src/pages/ProductDetail.tsx|generateAplus",
    "client": "generateProductAplus",
    "endpoint": "`/products/${id}/aplus/generate`",
    "method": "post",
    "source": "frontend/src/pages/ProductDetail.tsx",
    "handler": "generateAplus",
    "via": "direct"
  },
  {
    "id": "importLocalEnvConfig|frontend/src/components/LocalEnvConfigTable.tsx|importConfig",
    "client": "importLocalEnvConfig",
    "endpoint": "'/config/local-env/import'",
    "method": "post",
    "source": "frontend/src/components/LocalEnvConfigTable.tsx",
    "handler": "importConfig",
    "via": "direct"
  },
  {
    "id": "importUpcPool|frontend/src/pages/UpcPoolPage.tsx|handleAdd",
    "client": "importUpcPool",
    "endpoint": "'/products/upc-pool/import'",
    "method": "post",
    "source": "frontend/src/pages/UpcPoolPage.tsx",
    "handler": "handleAdd",
    "via": "direct"
  },
  {
    "id": "markTaskRunInterrupted|frontend/src/pages/TaskRunCenter.tsx|markInterrupted",
    "client": "markTaskRunInterrupted",
    "endpoint": "`/task-runs/${id}/mark-interrupted`",
    "method": "post",
    "source": "frontend/src/pages/TaskRunCenter.tsx",
    "handler": "markInterrupted",
    "via": "direct"
  },
  {
    "id": "openProductFile|frontend/src/pages/ProductDetail.tsx|openPath",
    "client": "openProductFile",
    "endpoint": "`/products/${id}/files/open`",
    "method": "post",
    "source": "frontend/src/pages/ProductDetail.tsx",
    "handler": "openPath",
    "via": "direct"
  },
  {
    "id": "pauseOfflineTask|frontend/src/pages/OfflineTaskCenter.tsx|pauseTask",
    "client": "pauseOfflineTask",
    "endpoint": "`/offline-tasks/${id}/pause`",
    "method": "post",
    "source": "frontend/src/pages/OfflineTaskCenter.tsx",
    "handler": "pauseTask",
    "via": "direct"
  },
  {
    "id": "pausePipeline|frontend/src/pages/ProductDetail.tsx|ProductDetail|1",
    "client": "pausePipeline",
    "endpoint": "`/products/${id}/pause`",
    "method": "post",
    "source": "frontend/src/pages/ProductDetail.tsx",
    "handler": "ProductDetail",
    "via": "direct"
  },
  {
    "id": "pausePipeline|frontend/src/pages/ProductDetail.tsx|ProductDetail|2",
    "client": "pausePipeline",
    "endpoint": "`/products/${id}/pause`",
    "method": "post",
    "source": "frontend/src/pages/ProductDetail.tsx",
    "handler": "ProductDetail",
    "via": "direct"
  },
  {
    "id": "pausePipeline|frontend/src/pages/ProductList.tsx|suspendProductTask",
    "client": "pausePipeline",
    "endpoint": "`/products/${id}/pause`",
    "method": "post",
    "source": "frontend/src/pages/ProductList.tsx",
    "handler": "suspendProductTask",
    "via": "direct"
  },
  {
    "id": "regenerateAplusModule|frontend/src/pages/ProductDetail.tsx|regenerateAplus",
    "client": "regenerateAplusModule",
    "endpoint": "`/products/${id}/aplus/regenerate`",
    "method": "post",
    "source": "frontend/src/pages/ProductDetail.tsx",
    "handler": "regenerateAplus",
    "via": "direct"
  },
  {
    "id": "rerunOfflineTask|frontend/src/pages/OfflineTaskCenter.tsx|rerunTask",
    "client": "rerunOfflineTask",
    "endpoint": "`/offline-tasks/${id}/rerun`",
    "method": "post",
    "source": "frontend/src/pages/OfflineTaskCenter.tsx",
    "handler": "rerunTask",
    "via": "direct"
  },
  {
    "id": "restartPipeline|frontend/src/pages/ProductDetail.tsx|doRestart",
    "client": "restartPipeline",
    "endpoint": "`/products/${id}/restart`",
    "method": "post",
    "source": "frontend/src/pages/ProductDetail.tsx",
    "handler": "doRestart",
    "via": "direct"
  },
  {
    "id": "restartPipeline|frontend/src/pages/ProductList.tsx|render",
    "client": "restartPipeline",
    "endpoint": "`/products/${id}/restart`",
    "method": "post",
    "source": "frontend/src/pages/ProductList.tsx",
    "handler": "render",
    "via": "direct"
  },
  {
    "id": "resumeOfflineTask|frontend/src/pages/OfflineTaskCenter.tsx|resumeTask",
    "client": "resumeOfflineTask",
    "endpoint": "`/offline-tasks/${id}/resume`",
    "method": "post",
    "source": "frontend/src/pages/OfflineTaskCenter.tsx",
    "handler": "resumeTask",
    "via": "direct"
  },
  {
    "id": "resumePipeline|frontend/src/pages/ProductDetail.tsx|ProductDetail|1",
    "client": "resumePipeline",
    "endpoint": "`/products/${id}/resume`",
    "method": "post",
    "source": "frontend/src/pages/ProductDetail.tsx",
    "handler": "ProductDetail",
    "via": "direct"
  },
  {
    "id": "resumePipeline|frontend/src/pages/ProductDetail.tsx|ProductDetail|2",
    "client": "resumePipeline",
    "endpoint": "`/products/${id}/resume`",
    "method": "post",
    "source": "frontend/src/pages/ProductDetail.tsx",
    "handler": "ProductDetail",
    "via": "direct"
  },
  {
    "id": "resumePipeline|frontend/src/pages/ProductDetail.tsx|runWorkflowAction",
    "client": "resumePipeline",
    "endpoint": "`/products/${id}/resume`",
    "method": "post",
    "source": "frontend/src/pages/ProductDetail.tsx",
    "handler": "runWorkflowAction",
    "via": "workflow_registry"
  },
  {
    "id": "resumePipeline|frontend/src/pages/ProductList.tsx|resumeProductTask",
    "client": "resumePipeline",
    "endpoint": "`/products/${id}/resume`",
    "method": "post",
    "source": "frontend/src/pages/ProductList.tsx",
    "handler": "resumeProductTask",
    "via": "direct"
  },
  {
    "id": "resumePipeline|frontend/src/pages/ProductList.tsx|runProductWorkflowAction",
    "client": "resumePipeline",
    "endpoint": "`/products/${id}/resume`",
    "method": "post",
    "source": "frontend/src/pages/ProductList.tsx",
    "handler": "runProductWorkflowAction",
    "via": "workflow_registry"
  },
  {
    "id": "retryAplusRegeneration|frontend/src/pages/ProductDetail.tsx|retryInterruptedAplus",
    "client": "retryAplusRegeneration",
    "endpoint": "`/products/${id}/aplus/regenerate/retry`",
    "method": "post",
    "source": "frontend/src/pages/ProductDetail.tsx",
    "handler": "retryInterruptedAplus",
    "via": "direct"
  },
  {
    "id": "retryFailedTaskRunSteps|frontend/src/pages/TaskRunCenter.tsx|retryRun",
    "client": "retryFailedTaskRunSteps",
    "endpoint": "`/task-runs/${id}/retry-failed`",
    "method": "post",
    "source": "frontend/src/pages/TaskRunCenter.tsx",
    "handler": "retryRun",
    "via": "direct"
  },
  {
    "id": "retryProductAutoImageSelection|frontend/src/pages/ProductDetail.tsx|runWorkflowAction",
    "client": "retryProductAutoImageSelection",
    "endpoint": "`/products/${id}/auto-image-selection/retry`",
    "method": "post",
    "source": "frontend/src/pages/ProductDetail.tsx",
    "handler": "runWorkflowAction",
    "via": "workflow_registry"
  },
  {
    "id": "retryProductAutoImageSelection|frontend/src/pages/ProductList.tsx|runProductWorkflowAction",
    "client": "retryProductAutoImageSelection",
    "endpoint": "`/products/${id}/auto-image-selection/retry`",
    "method": "post",
    "source": "frontend/src/pages/ProductList.tsx",
    "handler": "runProductWorkflowAction",
    "via": "workflow_registry"
  },
  {
    "id": "retryProductCompetitorSearch|frontend/src/pages/ProductDetail.tsx|runWorkflowAction",
    "client": "retryProductCompetitorSearch",
    "endpoint": "`/products/${id}/competitor-search/retry`",
    "method": "post",
    "source": "frontend/src/pages/ProductDetail.tsx",
    "handler": "runWorkflowAction",
    "via": "workflow_registry"
  },
  {
    "id": "retryProductCompetitorSearch|frontend/src/pages/ProductList.tsx|runProductWorkflowAction",
    "client": "retryProductCompetitorSearch",
    "endpoint": "`/products/${id}/competitor-search/retry`",
    "method": "post",
    "source": "frontend/src/pages/ProductList.tsx",
    "handler": "runProductWorkflowAction",
    "via": "workflow_registry"
  },
  {
    "id": "retryProductCompetitorVisualMatch|frontend/src/pages/ProductDetail.tsx|runWorkflowAction",
    "client": "retryProductCompetitorVisualMatch",
    "endpoint": "`/products/${id}/competitor-visual-match/retry`",
    "method": "post",
    "source": "frontend/src/pages/ProductDetail.tsx",
    "handler": "runWorkflowAction",
    "via": "workflow_registry"
  },
  {
    "id": "retryProductCompetitorVisualMatch|frontend/src/pages/ProductList.tsx|runProductWorkflowAction",
    "client": "retryProductCompetitorVisualMatch",
    "endpoint": "`/products/${id}/competitor-visual-match/retry`",
    "method": "post",
    "source": "frontend/src/pages/ProductList.tsx",
    "handler": "runProductWorkflowAction",
    "via": "workflow_registry"
  },
  {
    "id": "retryStep|frontend/src/pages/ProductDetail.tsx|ProductDetail",
    "client": "retryStep",
    "endpoint": "`/products/${id}/retry`",
    "method": "post",
    "source": "frontend/src/pages/ProductDetail.tsx",
    "handler": "ProductDetail",
    "via": "direct"
  },
  {
    "id": "retryStep|frontend/src/pages/ProductDetail.tsx|runWorkflowAction",
    "client": "retryStep",
    "endpoint": "`/products/${id}/retry`",
    "method": "post",
    "source": "frontend/src/pages/ProductDetail.tsx",
    "handler": "runWorkflowAction",
    "via": "workflow_registry"
  },
  {
    "id": "retryStep|frontend/src/pages/ProductList.tsx|renderPrimaryRowAction|1",
    "client": "retryStep",
    "endpoint": "`/products/${id}/retry`",
    "method": "post",
    "source": "frontend/src/pages/ProductList.tsx",
    "handler": "renderPrimaryRowAction",
    "via": "direct"
  },
  {
    "id": "retryStep|frontend/src/pages/ProductList.tsx|renderPrimaryRowAction|2",
    "client": "retryStep",
    "endpoint": "`/products/${id}/retry`",
    "method": "post",
    "source": "frontend/src/pages/ProductList.tsx",
    "handler": "renderPrimaryRowAction",
    "via": "direct"
  },
  {
    "id": "retryStep|frontend/src/pages/ProductList.tsx|runProductWorkflowAction",
    "client": "retryStep",
    "endpoint": "`/products/${id}/retry`",
    "method": "post",
    "source": "frontend/src/pages/ProductList.tsx",
    "handler": "runProductWorkflowAction",
    "via": "workflow_registry"
  },
  {
    "id": "retryTaskStep|frontend/src/pages/TaskRunCenter.tsx|retryOneStep",
    "client": "retryTaskStep",
    "endpoint": "`/task-runs/steps/${id}/retry`",
    "method": "post",
    "source": "frontend/src/pages/TaskRunCenter.tsx",
    "handler": "retryOneStep",
    "via": "direct"
  },
  {
    "id": "runPipelineStep|frontend/src/pages/ProductDetail.tsx|generateCustomerMindset",
    "client": "runPipelineStep",
    "endpoint": "`/products/${id}/step/${step}`",
    "method": "post",
    "source": "frontend/src/pages/ProductDetail.tsx",
    "handler": "generateCustomerMindset",
    "via": "direct"
  },
  {
    "id": "runProductFromStep|frontend/src/pages/ProductDetail.tsx|regenerateListing",
    "client": "runProductFromStep",
    "endpoint": "`/products/${id}/run-from-step`",
    "method": "post",
    "source": "frontend/src/pages/ProductDetail.tsx",
    "handler": "regenerateListing",
    "via": "direct"
  },
  {
    "id": "runProductFromStep|frontend/src/pages/ProductDetail.tsx|retryInterruptedPipeline",
    "client": "runProductFromStep",
    "endpoint": "`/products/${id}/run-from-step`",
    "method": "post",
    "source": "frontend/src/pages/ProductDetail.tsx",
    "handler": "retryInterruptedPipeline",
    "via": "direct"
  },
  {
    "id": "updateCatalogTemplateFileStatus|frontend/src/pages/CatalogList.tsx|toggleTemplateFile",
    "client": "updateCatalogTemplateFileStatus",
    "endpoint": "`/products/catalog/template-files/${fileId}/status`",
    "method": "patch",
    "source": "frontend/src/pages/CatalogList.tsx",
    "handler": "toggleTemplateFile",
    "via": "direct"
  },
  {
    "id": "updateConfig|frontend/src/pages/ConfigPage.tsx|saveConfig",
    "client": "updateConfig",
    "endpoint": "'/config'",
    "method": "patch",
    "source": "frontend/src/pages/ConfigPage.tsx",
    "handler": "saveConfig",
    "via": "direct"
  },
  {
    "id": "updateLocalEnvValue|frontend/src/components/LocalEnvConfigTable.tsx|saveValue",
    "client": "updateLocalEnvValue",
    "endpoint": "`/config/local-env/${encodeURIComponent(key)}`",
    "method": "patch",
    "source": "frontend/src/components/LocalEnvConfigTable.tsx",
    "handler": "saveValue",
    "via": "direct"
  },
  {
    "id": "updateProduct|frontend/src/pages/ProductDetail.tsx|saveCategory",
    "client": "updateProduct",
    "endpoint": "`/products/${id}`",
    "method": "patch",
    "source": "frontend/src/pages/ProductDetail.tsx",
    "handler": "saveCategory",
    "via": "direct"
  },
  {
    "id": "updateProduct|frontend/src/pages/ProductDetail.tsx|saveListing",
    "client": "updateProduct",
    "endpoint": "`/products/${id}`",
    "method": "patch",
    "source": "frontend/src/pages/ProductDetail.tsx",
    "handler": "saveListing",
    "via": "direct"
  },
  {
    "id": "updateProductDataSource|frontend/src/pages/ProductDataSourceList.tsx|save",
    "client": "updateProductDataSource",
    "endpoint": "`/product-data-sources/${id}`",
    "method": "patch",
    "source": "frontend/src/pages/ProductDataSourceList.tsx",
    "handler": "save",
    "via": "direct"
  },
  {
    "id": "updateProductListingImages|frontend/src/pages/ProductDetail.tsx|saveListingImagePaths",
    "client": "updateProductListingImages",
    "endpoint": "`/products/${id}/listing-images`",
    "method": "put",
    "source": "frontend/src/pages/ProductDetail.tsx",
    "handler": "saveListingImagePaths",
    "via": "direct"
  },
  {
    "id": "updateProductListingImages|frontend/src/pages/ProductImageReview.tsx|saveAndNext",
    "client": "updateProductListingImages",
    "endpoint": "`/products/${id}/listing-images`",
    "method": "put",
    "source": "frontend/src/pages/ProductImageReview.tsx",
    "handler": "saveAndNext",
    "via": "direct"
  },
  {
    "id": "uploadCatalogCategoryTemplate|frontend/src/pages/CatalogList.tsx|uploadTemplateForCategory",
    "client": "uploadCatalogCategoryTemplate",
    "endpoint": "'/products/catalog/category-template-upload'",
    "method": "post",
    "source": "frontend/src/pages/CatalogList.tsx",
    "handler": "uploadTemplateForCategory",
    "via": "direct"
  },
  {
    "id": "wakeTaskRun|frontend/src/pages/TaskRunCenter.tsx|wakeRun",
    "client": "wakeTaskRun",
    "endpoint": "`/task-runs/${id}/wake`",
    "method": "post",
    "source": "frontend/src/pages/TaskRunCenter.tsx",
    "handler": "wakeRun",
    "via": "direct"
  }
] as const satisfies readonly MutationCallsite[];

export const mutationExportExceptions = [
  {
    "client": "autoStartReadyGeneration",
    "classification": "unused",
    "reason": "The automatic ready-generation client is not currently exposed by a pages/components/hooks owner."
  },
  {
    "client": "bulkStartPipelines",
    "classification": "unused",
    "reason": "The legacy direct bulk-start client has no current pages/components/hooks owner; task-based advance is used instead."
  },
  {
    "client": "clearCatalogAsin",
    "classification": "unused",
    "reason": "Catalog ASIN deletion is not currently exposed by a pages/components/hooks owner."
  },
  {
    "client": "confirmProduct",
    "classification": "unused",
    "reason": "The legacy product confirmation client has no current pages/components/hooks owner."
  },
  {
    "client": "createAplusUploadBatch",
    "classification": "unused",
    "reason": "A+ upload batch creation is not currently exposed by a pages/components/hooks owner."
  },
  {
    "client": "createAsinSyncBatch",
    "classification": "unused",
    "reason": "ASIN sync creation is not currently exposed by a pages/components/hooks owner."
  },
  {
    "client": "createInventorySyncBatch",
    "classification": "unused",
    "reason": "The legacy inventory sync batch client has no current owner; task-run based GIGA inventory sync is active."
  },
  {
    "client": "createProductBulkAdvanceTask",
    "classification": "unused",
    "reason": "The explicit-id bulk advance client has no current pages/components/hooks owner; the filter-based owner is active."
  },
  {
    "client": "exportCatalogProducts",
    "classification": "unused",
    "reason": "The legacy direct catalog blob export is retained, while the current CatalogList owner creates task runs."
  },
  {
    "client": "exportCatalogProductsByCategory",
    "classification": "unused",
    "reason": "The legacy category blob export is retained, while the current CatalogList owner creates task runs."
  },
  {
    "client": "exportInventoryUpdateTemplate",
    "classification": "unused",
    "reason": "The inventory-template export client currently has no pages/components/hooks owner."
  },
  {
    "client": "importProducts",
    "classification": "unused",
    "reason": "The upload client remains available for compatibility, but no current pages/components/hooks owner invokes it."
  },
  {
    "client": "refreshProductFromGiga",
    "classification": "unused",
    "reason": "The direct product refresh client has no current pages/components/hooks owner."
  },
  {
    "client": "syncGigaInventory",
    "classification": "unused",
    "reason": "The direct GIGA inventory sync client has no current owner; task-run based sync is active."
  },
  {
    "client": "syncGigaPrice",
    "classification": "unused",
    "reason": "The direct GIGA price sync client has no current owner; task-run based sync is active."
  },
  {
    "client": "syncMissingGigaProducts",
    "classification": "unused",
    "reason": "The synchronous missing-product client has no current owner; the task-run pull client is active."
  },
  {
    "client": "syncMissingGigaProductsBackground",
    "classification": "unused",
    "reason": "The legacy background missing-product client has no current pages/components/hooks owner."
  },
  {
    "client": "updateCatalogAsin",
    "classification": "unused",
    "reason": "Catalog ASIN mutation is not currently exposed by a pages/components/hooks owner."
  }
] as const;

export const mutationInventoryFoundationStatus = {
  inventory_owner_contract: 'enabled',
  d2b_static_wrapper_coverage: 'enabled',
  d2b_runtime_playwright_coverage: 'enabled',
} as const;
