/* This file is generated by scripts/generate-product-workflow-actions.mjs. */
export const PRODUCT_WORKFLOW_ACTIONS = [
  {
    "action": "manual_adjust_images",
    "kind": "navigate",
    "target": "/products/image-review?product_id={product_id}",
    "default_label": "手动调图"
  },
  {
    "action": "open_detail",
    "kind": "navigate",
    "target": "/products/{product_id}",
    "default_label": "查看"
  },
  {
    "action": "open_export_center",
    "kind": "navigate",
    "target": "/export-center",
    "default_label": "导出中心"
  },
  {
    "action": "open_image_review",
    "kind": "navigate",
    "target": "/products/image-review?product_id={product_id}",
    "default_label": "确认图片"
  },
  {
    "action": "open_task_center",
    "kind": "navigate",
    "target": "/task-runs?correlation_key={related_correlation_key}",
    "default_label": "任务中心"
  },
  {
    "action": "restart_competitor_search",
    "kind": "api",
    "client_export": "retryProductCompetitorSearch",
    "method": "POST",
    "route": "/api/products/{product_id}/competitor-search/retry",
    "default_label": "重新搜索竞品"
  },
  {
    "action": "resume",
    "kind": "api",
    "client_export": "resumePipeline",
    "method": "POST",
    "route": "/api/products/{product_id}/resume",
    "default_label": "继续"
  },
  {
    "action": "retry",
    "kind": "api",
    "client_export": "retryStep",
    "method": "POST",
    "route": "/api/products/{product_id}/retry",
    "default_label": "重试"
  },
  {
    "action": "retry_auto_image_selection",
    "kind": "api",
    "client_export": "retryProductAutoImageSelection",
    "method": "POST",
    "route": "/api/products/{product_id}/auto-image-selection/retry",
    "default_label": "重试自动选图"
  },
  {
    "action": "retry_competitor_search",
    "kind": "api",
    "client_export": "retryProductCompetitorSearch",
    "method": "POST",
    "route": "/api/products/{product_id}/competitor-search/retry",
    "default_label": "重试 Amazon 搜索"
  },
  {
    "action": "retry_competitor_visual_match",
    "kind": "api",
    "client_export": "retryProductCompetitorVisualMatch",
    "method": "POST",
    "route": "/api/products/{product_id}/competitor-visual-match/retry",
    "default_label": "重试视觉初筛"
  },
  {
    "action": "retry_image_analysis",
    "kind": "api",
    "client_export": "retryStep",
    "method": "POST",
    "route": "/api/products/{product_id}/retry",
    "default_label": "重试图片分析"
  },
  {
    "action": "retry_listing_generation",
    "kind": "api",
    "client_export": "retryStep",
    "method": "POST",
    "route": "/api/products/{product_id}/retry",
    "default_label": "重试 Listing"
  },
  {
    "action": "start_competitor_search",
    "kind": "api",
    "client_export": "retryProductCompetitorSearch",
    "method": "POST",
    "route": "/api/products/{product_id}/competitor-search/retry",
    "default_label": "开始搜索"
  }
] as const;

export type GeneratedProductWorkflowAction = typeof PRODUCT_WORKFLOW_ACTIONS[number]['action'];
